# Generated by Django 4.2.7 on 2025-10-17 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='meetingrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='meeting',
        ),
        migrations.RenameField(
            model_name='meetingroom',
            old_name='is_chat_enabled',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='is_audio_enabled',
        ),
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='is_video_enabled',
        ),
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='left_at',
        ),
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='role',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='is_recording_enabled',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='is_screen_share_enabled',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='password',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='scheduled_end',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='scheduled_start',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='status',
        ),
        migrations.AlterField(
            model_name='meetingparticipant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='MeetingRequest',
        ),
        migrations.DeleteModel(
            name='Recording',
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='video_app.meetingroom'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('meeting', 'user')},
        ),
    ]
